# Generated by Django 3.0 on 2021-03-16 11:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_verifyemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='fulldetail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
