# Generated by Django 3.0 on 2021-03-16 12:03

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20210316_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='fulldetail',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
