# Generated by Django 3.0 on 2021-04-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20210428_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Express',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expname', models.CharField(default='', max_length=200)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
