# Generated by Django 3.0 on 2021-04-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_express'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpending',
            name='silptime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
