# Generated by Django 3.0 on 2021-04-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20210428_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Express',
        ),
    ]
