# Generated by Django 3.0 on 2021-04-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_delete_express'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpending',
            name='silptime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
